"""empty message

Revision ID: 0514a80c281a
Revises: c20c9658b1f5
Create Date: 2023-12-19 11:15:25.253958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0514a80c281a'
down_revision: Union[str, None] = 'c20c9658b1f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basket', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('basket', sa.Column('product_id', sa.String(), nullable=False))
    op.drop_column('basket', 'maker')
    op.drop_column('basket', 'id')
    op.drop_column('basket', 'img')
    op.drop_column('basket', 'characteristic')
    op.drop_column('basket', 'variety')
    op.drop_column('basket', 'availability')
    op.drop_column('basket', 'name')
    op.drop_column('basket', 'type')
    op.drop_column('basket', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basket', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('basket', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('basket', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('basket', sa.Column('availability', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('basket', sa.Column('variety', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('basket', sa.Column('characteristic', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('basket', sa.Column('img', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('basket', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('basket', sa.Column('maker', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('basket', 'product_id')
    op.drop_column('basket', 'user_id')
    # ### end Alembic commands ###
